### ISSUE TITLE
Exception when reached file limit

### ISSUE THREAD

**Issue by securigy** [MarkLTX/TracerX#5]
Got this unhandled exception out of the blue... and it i snot the first time I run my app... I guess it reached 10 filles that I set...

An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_10.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_09.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_09.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_08.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_08.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_07.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_07.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_06.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_06.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_05.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_05.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_04.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_04.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_03.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
An exception occurred while renaming the old log file 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_03.tx1 
to 
C:\Projects\DTDesktopExtension\DesktopAutomation\DesktopAutomation\bin\Debug\Logs\DesktopAutomationLog_02.tx1 

System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at TracerX.FileBase.TryRename(String from, String basePath, Int32 num)
The thread 0x2024 has exited with code 0 (0x0).
20:28:05.409 Verbose Main Thread Program+ Another DesktopAutomation application instance is already running, exiting...
The program '[20672] DesktopAutomation.exe' has exited with code 0 (0x0).

**Comment by MarkLTX** [comment]
This is a very old issue that I think has been fixed in later releases.  I can't reproduce it so unless somebody besides me is still seeing this I will probably close this soon.

**Comment by securigy** [comment]
Hi Mark, so I have been using your latest version and in most cases it handled async/await pattern OK when working under Visual Studio. However, lately I shipped the app to my beta tester, and one of the exceptions is as depicted in screenshot... Seems like something is still wrong...[
![image](https://user-images.githubusercontent.com/22898824/215165804-6db5f90c-cdca-4a49-b2c5-9e2a63cba8f4.png)
](url)

**Comment by MarkLTX** [comment]
Sorry about that.  

Is there any chance you could provide sample code that reproduces this issue?

It looks like thread 2 was awaiting the task that was running thread 4, the exception was thrown in thread 4 and captured by the Task object, and then re-thrown as an AggregateException in thread 2 when it tried to access the Task.Result.  Does that seem right to you?

BTW, this probably should have been a new issue.

**Comment by securigy** [comment]
Sorry about 'new issue'.I will try to provide the source - it is while accessing async API of DALL E 2
    On Saturday, January 28, 2023 at 10:21:34 AM PST, MarkLTX ***@***.***> wrote:  
 
 


Sorry about that.

Is there any chance you could provide sample code that reproduces this issue?

It looks like thread 2 was awaiting the task that was running thread 4, the exception was thrown in thread 4 and captured by the Task object, and then re-thrown as an AggregateException in thread 2 when it tried to access the Task.Result. Does that seem right to you?

BTW, this probably should have been a new issue.

**Comment by MarkLTX** [comment]
I haven't been able to reproduce this yet.  Which version of .NET are you targeting?

**Comment by securigy** [comment]
I am using 4.8
    On Monday, January 30, 2023 at 07:09:35 AM PST, MarkLTX ***@***.***> wrote:  
 
 


I haven't been able to reproduce this yet. Which version of .NET are you targeting?

**Comment by MarkLTX** [comment]
Please check the properties of your reference to TracerX-Logger.dll and confirm it's referencing the 'net46' version.  That is, the path should end with something like this: "\packages\TracerX-Logger.8.0.0\lib\net46\TracerX-Logger.dll".  Note the "net46" folder.
